gradebook/server

lib/api/category.js
lib/controllers/category.js
lib/controllers/user.js

This updates the category.new API and controller layer to what I think it should be.
Sorry if I wasn't clear earlier, the API layer should only get data that's allowed, in the database. Even though the data is considered "safe", we still have that restriction.
I fixed the transaction usage in the user.approve controller method, let me know if there's anything that doesn't make sense.

Only pass good data to API layer

---

lib/cache/settings.js
lib/services/permissions/batch-edit-grades.js
lib/services/permissions/create-category.js
lib/services/permissions/create-course.js
lib/services/permissions/create-grade.js
test/unit/permissions.js

The maximum grade and category limits were somewhat inconsistent in terminology and usage. I've made it so it should makes sense now. I've have also set the limits as such:
- `max_courses_per_semester` = 7 (no change)
- `max_categories_per_course` = 25 (down from 30)
- `max_grades_per_category` = 40
Upped grade max to 40 because of several people's request! I'll also make a frontend PR once this is live.

Increase grade and category limits

---

lib/api/course.js
lib/api/semester.js

This updates semester.delete to actually delete courses rather than update the status to 0. 
Things that need to happen:
- Delete all courses and course data in prod db with status of 0 (very important bc this broke the client for me in testing)
- remove status column from db and migrate

Update semester.delete API to actually delete data and use actions

---

lib/api/category.js
package.json
yarn.lock

This implements the `@gradebook/fast-pluralize` package to fix the issue with improper singularization on category expansion.

Fix singularization in category expansion

---

lib/api/category.js
lib/controllers/category.js
lib/services/permissions/contract-category.js
lib/services/permissions/index.js
lib/services/validation/contract-category.js
lib/services/validation/index.js
lib/services/validation/schema-validator.js
lib/services/validation/schemas/contract-category.json
lib/web/app.js
test/unit/permissions.js
test/unit/schemas/contract-category.js

__As this is an `epic` change, both @ramsays and @joshcosta need to approve the PR__
`POST /api/v0/category/:id/contract`
Accepts: `{grade: number}`
Response: `{id: string, name: null, grade: number}`
The response contains the only grade associated with `category.id` and the updated properties (`name`, `grade`).
This has been a highly requested feature.

✨ add category.contract endpoint

---

lib/api/category.js
lib/controllers/category.js
lib/controllers/sanitizers/category.js
lib/services/validation/schemas/create-category.json
lib/services/validation/schemas/edit-category.json

Resolves #1 
Adding dropped-grades to schema. Does not require a database migration since it already exists, just needs to expose the field in the API and validation.

:building_construction: expose category.dropped_grades (as dropped) CRUD

---

config.testing.json
lib/controllers/grade.js
lib/services/validation/schemas/batch-edit.json
lib/services/validation/schemas/create-grade.json
lib/services/validation/schemas/edit-grade.json
test/functional/routes.spec.js
test/unit/schemas/create-grade.js
test/unit/schemas/edit-grade.js

Updates category.batch, grade.create, and grade.edit to disallow `name: null` in the payload

Disallow null grade names

---

lib/services/validation/user-settings.js

This adds a user setting that stores the latest semester the user modified gpa settings. More info to come in client PR.
Note: Didn't need to add tests because user settings and the semester key validator are already covered.

:sparkles: add `gpaSemester` user setting

---

_commands/dev.js
config.example.json
lib/controllers/home.js
lib/frontend/assets/lr.js
lib/web/index.js
lib/web/live-reload.js
package.json
yarn.lock

The tl;dr is webpack dev server is very heavy, and this server is better. This definitely works, though there might be some edge cases.
Things to do once this is merged:
How to test:
- Add `"live reload": true` to your config, then run `yarn dev`
This PR requires 2 reviewers

🔧 enable server-side live reloading

---

lib/api/base.js
lib/api/user.js
lib/controllers/user.js
lib/models/create-row.js
lib/services/authentication/passport.js
package.json
yarn.lock

refs gradebook/utils#51
Things to test:
---
If you're up to it, also check what the session data is each time
I can't test creating a new user (no integration) at the moment, but I highly suspect that session cleanup is broken, and passport-utils cannot handle authenticating newly approved users.

:recycle: Consolidate auth logic to package

---

lib/utils/compute-statistics.js

Addresses issue that popped up in dev. The fix is flipping the execution order of the joins so that a reference to the `courses` table exists before trying to use it. 
I just need a once-over review to verify that this shouldn't change the end result of the query.
> [2020-06-23 23:58:00] ERROR Failed to insert statistics for "husker":
[2020-06-23 23:58:00] ERROR select count(`categories`.`id`) as `totalCategories` from `husker`.`categories` inner join `husker`.`users` on `courses`.`user_id` = `users`.`id` and 1 = 0 inner join `husker`.`courses` on `courses`.`id` = `categories`.`course_id` and `courses`.`semester` = '2020U' limit 1 - ER_BAD_FIELD_ERROR: Unknown column 'courses.user_id' in 'on clause'
select count(`categories`.`id`) as `totalCategories` from `husker`.`categories` inner join …

:bug: fix sql join order to prevent stats failure

---

lib/services/validation/create-course.js
lib/services/validation/schemas/legacy-create-course.json
test/unit/validation.spec.js

Allows courses marked as escaped to include an empty cutoffs object. The request query parameter "type" is used to mark courses as escaped.
req.query.type options:
- "partial": Escaped from course creator. Must have empty cutoffs object.
- "guided": Finished course creator. Cutoffs validated as usual.
- "import": Course is an import. Cutoffs validated as usual.
- else: Cutoffs still validated as usual.
Unit tests check that escaped courses must have an empty cutoffs object, and all other courses must have actual cutoffs.
Meta:
- 1 reviewer
- rebase

✨ support escaped courses

---

lib/services/permissions/batch-edit-grades.js
lib/services/permissions/create-category.js
lib/services/permissions/create-course.js
lib/services/permissions/create-grade.js
lib/services/settings/base-adapter.js
lib/services/settings/index.js
lib/services/validation/create-category.js
lib/services/validation/shared/create-course.js

- Centralize default values to abstract settings store
- Improve types
- Sync max course count with what we have in prod
@joshcosta - Ramsay and I have updated our settings table, you need to do so as well. Pick your query:
```sql
DELETE FROM settings WHERE key != "session_secret"; -- On init, adapter will populate defaults that are missing
-- OR
update settings set value=8 where key="max_courses_per_semester";
```
Reviewers: 1 + 1 (1 needed for merge, but everyone should review it)
Merge Type: rebase

Improvements to settings service

---

.github/workflows/ci.yml
lib/api/base.js
lib/api/category.js
lib/api/course.js
lib/api/grade.js
lib/api/semester.js
lib/api/user.js
lib/controllers/course.js
lib/controllers/user.js
scripts/initialize-test-db.js
test/functional/api.spec.js
test/functional/routes.spec.js
test/global.js
test/utils/index.js
test/utils/schema-validator.js
test/utils/test-config.js

closes #190
- database no longer defaults to null in any api calls
- method signature is updated to always have database first and then txn
reviewers: 1 + 1

🔧update api method signatures to require database

---

config.example.json
lib/controllers/course.js
lib/controllers/home.js
lib/services/internal-auth.js
lib/services/shrink.js
lib/services/validation/create-course.js
package.json
yarn.lock

To test:
1. Add a resolver in gateway for shrink
2. Add a client in shrink for server, with permission to access shrink
3. Update your server config to have `"gateway": "http://{client_id}:{client_secret}@{gateway_ip}:{gateway_port}"`
4. Start gateway and shrink
5. Go to `{server}/my/import?slug=abcd`
6. ~~Note: Shrink does not have support for returning slug payloads yet. E2E integration will happen later.~~ in progress

✨ add initial support for shrink (course-search) integration

---

lib/controllers/authentication/with-user.js

refs gradebook/engineering#77
Example:
1. User visits a URL but is not authenticated (e.g. `https://aggie.gradebook.app/my/dashboard`)
2. Internally, the user is redirected to `/login`
3. The user logs in to an account associated with another school (e.g. `the`)
4. Internally, the client fetches `/api/v0/me`
5. Current behavior: server redirects to e.g. `https://the.gradebook.app/api/v0/me`
6. This is a cross-origin request, so the browser sends an OPTIONS request to `https://the.gradebook.app/api/v0/me`
7. We explicitly don't allow cors between subdomains to limit unintended attack surfaces &rarr; request fails
8. Since the request failed, nothing changes
Ideally, we would use `fetch('/api/v0/me', {redirect: 'manual'})`, but the response will be an …

🏗️ use JSON redirect instead of HTTP redirect for `/me` API endpoint

---

lib/services/validation/user-settings.js

Add new user setting to allow semester display names to be shifted to match southern hemisphere seasons.
Reviewers: 1
Merge: Squash

Add backend support for Kangaroo mode

---

.github/workflows/ci.yml
.github/workflows/contract.yml

Maintain a single source of truth instead of having it in multiple places.
No reviewers, CI only

use package.json#engines.node for actions

---

lib/services/validation/schemas/user-gpa-settings.json
test/unit/schemas/user-gpa-settings.spec.js

In allowing for decimal credit hours on courses, we forgot to allow partial credit hours for overall GPA.

Allow for decimal gpa overall credits

---

.github/workflows/ci.yml

- move the job aggregation logic from our deployment service to GitHub Actions
- note: the deployment service will need to update the required jobs to a single `deploy` job

simplify release process
