gradebook/server

lib/web/redirects.js

Sponsor Redirect

---

lib/api/category.js
lib/api/course.js
lib/api/grade.js
lib/api/user.js
lib/database/migrations/versions/2.2/1-modify-stats-table.js
lib/services/analytics/history-queue.js
lib/services/cron/jobs.js
package.json

This PR will need some work and review. It involves a database migration so I'd like confirmation on if that goes smoothly. Other than that, the stats should be working. 
@vikaspotluri123 can we put this live somewhere so I can test the time zone management of the queries with a production-style db?

Add statistics logging

---

lib/api/frontend.js

@joshcosta this should (in theory) fix the issue you were having with local dev. Will also make the preview api work a bit better

Add fallback for frontend template not existing

---

_commands/_precheck.js
_commands/setup.js
lib/api/base.js
lib/cache/store.js
lib/controllers/version.js
lib/database/migrations/hooks/init/shutdown.js
lib/database/migrations/hooks/migrate/shutdown.js
lib/services/analytics/history-queue.js
lib/services/authentication/passport.js
lib/services/permissions/wrap.js
lib/utils/semester-key-valid.js
package.json
scripts/initialize-test-db.js
test/fixtures/example-data.js
yarn.lock

No need for approval, just checking that CI still passes

Bump deps, lint

---

lib/api/category.js
lib/controllers/category.js
lib/controllers/user.js

This PR is backend work needed for the upcoming frontend onboarding. 
My biggest question here is how I should use knex transactions in this situation.

Update user.approved fixtures to include some grades

---

.github/workflows/ci.yml
_commands/_precheck.js
config.example.json
lib/models/create-row.js
lib/utils/timezone-offset.js
package.json

Bump Node Version

---

lib/controllers/authentication/incoming.js
lib/controllers/authentication/index.js
lib/controllers/authentication/update-user-session.js
lib/controllers/home.js
lib/services/analytics/index.js
lib/services/analytics/user-logged-in.js
lib/services/analytics/user-session.js
lib/services/cron/jobs.js
lib/web/app.js

- planning on extending auth time, so sessions are more valuable than logging in
Do we want to also increment user.updated_at in the db when this is sent? updated_at currently only increments on login 😬

analytics: replace user.loggedIn with user.session

---

lib/api/category.js
package.json
yarn.lock

Refs https://github.com/gradebook/client/issues/2
Refs https://github.com/gradebook/client/pull/67
Once 67 gets merged, I'll update the submodule here, and squash + close the client issue.
if category.name == 'labs', category.grades[0, 1] = 'Lab {n+1}'

Singularize name when expanding a category

---

lib/controllers/authentication/with-user.js
lib/database/redis.js
lib/utils/get-session-store.js
test/unit/utils/get-limiter-store.js
test/unit/utils/get-session-store.js
test/unit/utils/semester-key-valid.js

Add some tests

---

lib/controllers/user.js
lib/services/validation/user-settings.js

move user.update_settings.key from req.body to req.query

---

lib/api/category.js
lib/controllers/category.js

🐛 fix category contraction in sqlite

---

config.example.json
lib/api/category.js
lib/api/course.js
lib/api/semester.js
lib/api/user.js
lib/controllers/course.js
lib/controllers/home.js
lib/controllers/user.js
lib/index.js
lib/services/host.js
lib/services/ignored-users.js
lib/utils/compute-statistics.js
lib/utils/current-semester.js

- :chart_with_upwards_trend: add support from blacklisting users from analytics
- update `compute-statistics` to use multiple lines per query
- Move current semester out of compute-statistics
- Definitely needs review from @joshcosta
- **This will be a rebase and merge**
I would like someone to sanity-check me that the queries haven't functionally changed.
<details>
<summary>Before / After (from debug)</summary>
Before:
```sql
knex:query select count(`id`) as `totalUsers` from `users` limit ? undefined +0ms
knex:bindings [ 1 ] undefined +0ms
knex:query select count(`id`) as `newUsers` from `users` where `created_at` >= ? limit ? undefined +3ms
knex:bindings [ '2020-06-07 01:58:00', 1 ] undefined +2ms
knex:query select count(`id`) as `newUsersLastWeek` from `users` where `created_at` >= ? …
```

Improvements to Statistics

---

lib/controllers/home.js
lib/controllers/sanitizers/user.js
lib/database/migrations/versions/3.10/5-rename-user-first-last-name.js

This PR requires **1** reviewer. Merge strategy: rebase

Rename user.firstName and user.lastName columns

---

lib/api/grade.js
lib/controllers/core-data.js
lib/controllers/user.js
lib/database/migrator.js
lib/services/current-semester.js
lib/services/permissions/batch-edit-grades.js
lib/services/permissions/contract-category.js
lib/services/permissions/create-category.js
lib/services/permissions/create-grade.js
lib/services/permissions/edit-category.js
lib/services/permissions/edit-course.js
lib/services/permissions/edit-grade.js
lib/services/permissions/expand-category.js
lib/services/validation/edit-category.js
lib/services/validation/edit-course.js
lib/services/validation/edit-grade.js
lib/utils/compute-statistics.js
lib/utils/current-semester.js
test/functional/routes.spec.js
test/global.js
test/unit/permissions.js

Enforce read-only semesters

---

lib/controllers/category.js
lib/database/commands.js
lib/database/schema.d.ts
lib/database/schema.js
lib/database/validator.js
lib/models/create-row.js
lib/models/database-response.js
test/unit/database/validator.js

- Almost everything is tested 🎉
- Schema is typed ✨
- Logic is easier to follow (though still not 100% easy) 🤓
- Support for more column types 🔹 
- Most integer types are now supported
- Most text types are now supported
- We should probably audit the current database structure and compare it w/ the structure of a newly created database and add any migrations that are needed 🗃
No need for a review, just creating the PR for history 📜
@joshcosta if you want to take a cursory glance that'd be 💯

Rework validation layer

---

lib/controllers/core-data.js
lib/services/cron/jobs.js
lib/services/current-semester.js
lib/services/permissions/batch-edit-grades.js
lib/services/permissions/contract-category.js
lib/services/permissions/create-category.js
lib/services/permissions/create-grade.js
lib/services/permissions/edit-category.js
lib/services/permissions/edit-course.js
lib/services/permissions/edit-grade.js
lib/services/permissions/expand-category.js
lib/utils/compute-statistics.js
test/global.js
test/unit/services/current-semester.js

refs #22 
Might be easier to review on a commit-by-commit basis

✨Add support for dynamically computing active semester

---

.github/workflows/ci.yml

[ci] bump actions/cache to v2

---

lib/api/base.js
lib/api/user.js
lib/database/commands.js
lib/database/migration-utils/column-migration.js
lib/database/migrations/000002-add-migration-count-column.js
lib/database/migrations/000003-add-last-donated-column.js
lib/database/schema.js
lib/services/serializers/database-response/user.js
lib/services/serializers/user.js

- `donated_at` used for donation tracking
- `total_school_changes` used for school migration tracking
Meta:
1 review required
rebase and merge

Add user migrations

---

.github/workflows/ci.yml
lib/api/course-types.d.ts
lib/api/course.js
lib/api/user-types.d.ts
lib/api/user.js
lib/database/index.js
lib/models/create-row.js
lib/models/database-response.js
test/fixtures/functional-user-export.js
test/functional/api.spec.js
test/utils/prepare-export.js

refs gradebook/engineering#15
Since course.create was refactored, the performance deltas (~6% loss using sqlite) are detailed in https://github.com/gradebook/engineering/issues/15#issuecomment-815171310
**Meta**
Reviewers: 2 (will merge after 1)
Merge Type: rebase

✨ add support for user imports

---

lib/controllers/user.js
lib/database/migrations/000006-user-tour-numeric-value.js
lib/services/validation/user-settings.js

refs gradebook/client#310
I'd like to get the review approval early because this includes a (relatively simple) migration
⚠ This requires a parallel merge + release of the client! ⚠ 
⚠ This cannot be merged until client is ready!            ⚠ 
**Meta**
Merge: Rebase
Reviewers: 1 + 1

Add support for multi-step tours

---

lib/services/school-config.js
lib/services/validation/user-settings.js

Related to [Client#379](https://github.com/gradebook/client/pull/379)
[Meta]
1 reviewer
Rebase

Add feedback semester to user settings

---

.github/workflows/contract.yml
package.json
test/contract/contract.spec.js
test/contract/dependencies.js
test/contract/ts-util.js

This is the output for a failing case, depends on gradebook/client#414 for a passing case
refs gradebook/client#409

Bootstrap support for contract tests

---

lib/api/user.js
lib/controllers/core-data.js
lib/controllers/home.js
lib/controllers/user.js
lib/models/create-row.js
lib/models/database-response.js
lib/services/analytics/history-queue.js
lib/services/permissions/batch-edit-grades.js
lib/services/permissions/complete-create-course.js
lib/services/permissions/create-category.js
lib/services/permissions/create-course.js
lib/services/permissions/create-grade.js
lib/services/permissions/edit-category.js
lib/services/permissions/edit-course.js
lib/services/permissions/edit-grade.js
lib/web/update-user-session.js
package.json
test/fixtures/example-data.js
test/functional/routes.spec.js
test/global.js
test/unit/permissions.spec.js
yarn.lock

- Provides primary and active semester data from `@gradebook/time:1.0.0` in core-data. 
- Uses new `serverAllowedSemesters` from `@gradebook/time` to check permissions. 
- Allows editing archived semesters
Archived semesters are semesters that are not active, and the new allowable actions are CRUD on archived grades and categories, and update on courses. Creating or completing creation of a course is still not allowed in archive.
The test fixtures are updated to allow for testing archived courses. Please re-run `initialize-test-db.js`.
Meta
1 reviewer
Rebase

Semester updates

---

config.example.json
lib/controllers/user.js
lib/security/hash.js
lib/services/permissions/index.js
lib/services/rate-limiting/index.js
lib/services/validation/index.js
lib/services/validation/schema-validator.js
lib/services/validation/schemas/user-issue-reporter.json
lib/services/validation/user-issue-reporter.js
lib/web/app.js

Validates and transforms data such that it can be processed and used by an internal service.
Includes timestamp-based request signing

✨ add user issue reporting route

---

lib/api/grade.js
lib/controllers/pipeline.js
lib/controllers/semester.js
lib/services/validation/batch-edit-grades.js
lib/services/validation/browse-categories.js
lib/services/validation/browse-courses.js
lib/services/validation/browse-grades.js
lib/services/validation/course-settings.js
lib/services/validation/create-category.js
lib/services/validation/create-course.js
lib/services/validation/edit-course.js
lib/services/validation/settings.js
lib/services/validation/shared/create-course.js
lib/services/validation/user-settings.js
lib/web/logging.js
test/functional/routes.spec.js
test/unit/validation.spec.js

refs gradebook/client#449 (since we want to surface validation errors to the user)
note: doesn't handle schema-based validators

Update copy for validation errors

---

lib/controllers/home.js

refs gradebook/engineering#79
- Includes a random seed to differentiate between restarts

✨ provide anonymous session number to client

---

global.d.ts
lib/controllers/user.js
lib/services/permissions/index.js
lib/services/validation/index.js
lib/services/validation/schema-validator.js
lib/services/validation/schemas/user-gpa-settings.json
lib/services/validation/user-settings-gpa.js
lib/services/validation/user-settings.js
lib/web/app.js
test/unit/schemas/user-gpa-settings.spec.js
test/unit/validation.spec.js

Add route to update GPA settings all at once

---

global.d.ts
lib/controllers/core-data.js
lib/controllers/version.js
lib/database/validator.js
lib/frontend/views/default.js
lib/frontend/views/error.js
lib/services/serializers/index.js
lib/utils/get-session-store.js
package.json
scripts/initialize-test-db.js
test/contract/contract.spec.js
test/contract/ts-util.js
test/unit/permissions.spec.js
yarn.lock

Functional tests are failing for me locally, checking if it's a flake or a real issue.

bump deps and lint

---

.github/workflows/ci.yml
lib/controllers/core-data.js
lib/controllers/home.js
test/functional/routes.spec.js

also changes semester data on core-data to be opt-in

add semester config meta tag

---

.github/workflows/ci.yml
_commands/_precheck.js
lib/controllers/internal.js
lib/controllers/user.js
lib/database/adapters/mysql.js
lib/database/adapters/sqlite3.js
lib/database/commands.js
lib/database/migrator.js
lib/errors/index.js
lib/frontend/assets/lr.js
lib/models/create-row.js
lib/security/hash.js
lib/services/analytics/history-queue.js
lib/services/authentication/passport.js
lib/services/global-store.js
lib/services/rate-limiting/limiter.js
lib/services/shrink.js
lib/utils/enhanced-fetch.js
lib/web/update-user-session.js
package.json
scripts/initialize-test-db.js
test/contract/contract.spec.js
test/functional/api.spec.js
test/functional/routes.spec.js
test/unit/models/user.spec.js
test/unit/utils/clear-cloudflare-cache.spec.js

- Yarn will report version mismatches
- XO will handle new features properly
review by-commit
merge: rebase

move node version to engines and bump node version

---

.github/workflows/ci.yml
dev-utils/routing.js
lib/api/frontend.js

chore: update frontend paths

---

.github/workflows/ci.yml

pin node in gradebook/actions

---

lib/database/migration-utils/alter-column.js
lib/database/migrations/000010-allow-decimal-course-credits.js
lib/database/migrations/000010-convert-course-credits-to-float.js
lib/database/schema.js

refs gradebook/engineering#106
Based on user feedback to allow for decimal course credits.
**Meta**
Reviewers: 1

add database support for decimal course credits

---

global.d.ts
lib/services/validation/user-settings.js

refs gradebook/client#527
Add user setting for global unlock, also fixed missed schema for kangaroo mode.
**Meta**
Reviewers: 1

Add backend support for global course unlock

---

lib/controllers/course.js

- now that we're embedding course search in course creator, any creation type can trigger a popularity increase

remove type check for popularity increment
